[tool.poetry]
name = "mypythoncrap"
version = "0.1.0"
description = ""
authors = ["Christian Goetz <cugoetz@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
request = "^2019.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
